# Generated by Django 5.2.7 on 2025-11-05 14:03

import django.db.models.deletion
import django.utils.timezone
import faculty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_facultyprofile_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docs', models.FileField(upload_to='docs/personal_docs/', validators=[faculty.models.validate_file_type])),
                ('title', models.CharField(max_length=100)),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_docs', to='faculty.facultyprofile')),
            ],
        ),
    ]
