# Generated by Django 5.2.7 on 2025-11-06 12:38

import django.db.models.deletion
import django.utils.timezone
import faculty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_rename_docs_personaldocs_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docs/assignments/', validators=[faculty.models.validate_file_type])),
                ('title', models.CharField(max_length=100)),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_assignment', models.DateField()),
                ('date_of_submission', models.DateField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='faculty.facultyprofile')),
            ],
        ),
    ]
