# Generated by Django 5.2.7 on 2025-11-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_assignmentdocs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docs/research')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(default='NA', max_length=50)),
                ('publication_date', models.DateField()),
                ('link', models.URLField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='faculty.facultyprofile')),
            ],
        ),
    ]
