# Generated by Django 5.2.7 on 2026-01-06 08:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_alter_facultyprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='profile_pics/d6r8kppjwtafmjw5mpup', max_length=255),
        ),
    ]
