# Generated by Django 5.2.7 on 2026-01-10 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_alter_facultyprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('organized_by', models.CharField(max_length=100)),
                ('role_type', models.CharField(choices=[('Participant', 'Participant'), ('Presented Research Paper', 'Presented Research Paper'), ('Keynote Speaker', 'Keynote Speaker'), ('Invited session chair', 'Invited session chair')], default='Participant', max_length=50)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='faculty.facultyprofile')),
            ],
        ),
    ]
