# Generated by Django 5.2.7 on 2025-11-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_facultyprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='department',
            field=models.CharField(default='Computer Science & Engineering', max_length=50),
        ),
    ]
