# Generated by Django 5.2.7 on 2025-11-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_personaldocs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldocs',
            old_name='docs',
            new_name='doc',
        ),
    ]
