# Generated by Django 5.2.7 on 2025-11-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_researchpublications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpublications',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
