# Generated by Django 5.2.7 on 2025-12-13 06:20

import cloudinary.models
import faculty.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_alter_researchpublications_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentdocs',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[faculty.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='profile_pics/default_profile', max_length=255),
        ),
        migrations.AlterField(
            model_name='personaldocs',
            name='doc',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[faculty.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='researchpublications',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
