# Generated by Django 5.2.7 on 2025-12-13 07:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_alter_assignmentdocs_file_alter_facultyprofile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='media/profile_pics/default_profile', max_length=255),
        ),
    ]
