# Generated by Django 5.2.7 on 2025-12-13 07:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_alter_facultyprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='profile_pics/default_profile', max_length=255),
        ),
    ]
